# Generated by Django 6.0.4 on 2026-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_institucional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='categoria',
            field=models.CharField(choices=[('ACADEMICO', 'Académicos'), ('CULTURAL', 'Culturales'), ('DEPORTIVO', 'Deportivos'), ('COMUNITARIO', 'Comunitarios')], default='ACADEMICO', max_length=20),
        ),
        migrations.AddField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='actividades/'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='lugar',
            field=models.CharField(default='I.E. Juana Cervantes', max_length=255),
        ),
    ]
