# Generated by Django 6.0.4 on 2026-05-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_institucional', '0004_perfil_dni_perfil_dni_hija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='dni_hija',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
