# Generated by Django 6.0.5 on 2026-05-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_institucional', '0006_alter_estudiante_nivel_alter_perfil_nivel_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='grado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='seccion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
