# Generated by Django 6.0.4 on 2026-05-13 18:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_actividad', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('INTERNA', 'Interna del Colegio'), ('EXTERNA', 'Participación Externa (Desfiles/Concursos)')], default='INTERNA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('LAPTOP', 'Laptop / Computadora'), ('SONIDO', 'Equipo de Sonido / Parlantes'), ('ELECTRO', 'Electrodoméstico'), ('ACCESORIO', 'Accesorio')], default='LAPTOP', max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('fecha_ingreso_colegio', models.DateField(verbose_name='Fecha de Ingreso/Donación')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=15)),
                ('aula_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('eliminado', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('es_general', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Designacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_responsable', models.CharField(max_length=150)),
                ('aula_destino', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('encargado_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='portal_institucional.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nivel', models.CharField(choices=[('PRI', 'Primaria'), ('SEC', 'Secundaria')], max_length=3)),
                ('grado', models.CharField(max_length=10)),
                ('seccion', models.CharField(max_length=1)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('b1', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('b2', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('b3', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('b4', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('promedio', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='portal_institucional.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador General'), ('DIRECTOR', 'Director del Colegio'), ('ENCAR', 'Profesor Encargado de Inventario'), ('DOCENTE', 'Docente Tutor'), ('SECRETARIA', 'Secretaria'), ('PADRE', 'Padre de Familia')], default='PADRE', max_length=20)),
                ('esta_aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('nivel_asignado', models.CharField(blank=True, choices=[('PRI', 'Primaria'), ('SEC', 'Secundaria')], max_length=3, null=True)),
                ('grado_asignado', models.CharField(blank=True, max_length=10, null=True)),
                ('seccion_asignada', models.CharField(blank=True, max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('TARDANZA', 'Tardanza')], max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='portal_institucional.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'fecha')},
            },
        ),
    ]
