# Generated by Django 6.0.4 on 2026-04-09 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento'), ('NO_EXISTE', 'No Existe / Dado de Baja')], default='DISPONIBLE', max_length=15)),
                ('fecha_ingreso_colegio', models.DateField(verbose_name='Fecha de ingreso al colegio')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente_recibe', models.CharField(max_length=150, verbose_name='Docente responsable')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_prevista', models.DateTimeField(verbose_name='Fecha prevista de devolución')),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha real de retorno')),
                ('encargado_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
            ],
            options={
                'verbose_name': 'Designación',
                'verbose_name_plural': 'Designaciones',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador General'), ('ENCAR', 'Profesor Encargado de Inventario'), ('SECRET', 'Secretario / Consulta')], default='SECRET', max_length=10)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
