# Generated by Django 6.0.4 on 2026-05-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_institucional', '0002_actividad_categoria_actividad_imagen_actividad_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='tipo',
            field=models.CharField(choices=[('GENERAL', 'Comunicado General'), ('AULA', 'Comunicado de Aula'), ('ATENCION', 'Llamada de Atención / Incidente')], default='GENERAL', max_length=20),
        ),
    ]
