# Generated by Django 6.0.4 on 2026-04-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_equipo_fecha_registro_sistema_equipo_registrado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='designacion',
            name='aula_destino',
            field=models.CharField(max_length=100, null=True, verbose_name='Aula'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='aula',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aula'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución Prevista'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='responsable',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Entregado a'),
        ),
    ]
