# Generated by Django 6.0.4 on 2026-05-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_institucional', '0003_comunicado_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI del Padre'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='dni_hija',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='DNI de la Hija'),
        ),
    ]
