# Generated by Django 6.0.4 on 2026-05-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_estudiante_remove_perfil_dni_equipo_equipo_padre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='eliminado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
