# Generated by Django 6.0.4 on 2026-05-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_equipo_eliminado_equipo_fecha_eliminacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('b1', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('b2', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('b3', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('b4', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('promedio', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.estudiante')),
            ],
        ),
    ]
