# Generated by Django 6.0.4 on 2026-05-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_institucional', '0005_alter_perfil_dni_alter_perfil_dni_hija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nivel',
            field=models.CharField(choices=[('SEC', 'Secundaria')], default='SEC', max_length=3),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nivel_asignado',
            field=models.CharField(blank=True, choices=[('SEC', 'Secundaria')], default='SEC', max_length=3, null=True),
        ),
    ]
