# Generated by Django 6.0.4 on 2026-05-06 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_actividad', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='equipo_padre',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(choices=[('LAPTOP', 'Laptop / Computadora'), ('SONIDO', 'Equipo de Sonido / Parlantes'), ('ELECTRO', 'Electrodoméstico'), ('ACCESORIO', 'Accesorio (Cargador, Mouse, etc.)'), ('OTROS', 'Otros')], default='LAPTOP', max_length=20),
        ),
        migrations.AddField(
            model_name='equipo',
            name='equipo_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesorios', to='inventario.equipo', verbose_name='Pertenece al equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='aula',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aula/Ubicación'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento'), ('NO_EXISTE', 'Baja / No Existe')], default='DISPONIBLE', max_length=15),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Devolución Prevista'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_ingreso_colegio',
            field=models.DateField(verbose_name='Ingreso al Colegio'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='responsable',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador General'), ('ENCAR', 'Profesor Encargado de Inventario'), ('DOCENTE', 'Docente tutor'), ('SECRET', 'Secretario / Consulta')], default='SECRET', max_length=20),
        ),
    ]
