# Generated by Django 6.0.4 on 2026-05-07 17:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_actividad_remove_equipo_equipo_padre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designacion',
            options={},
        ),
        migrations.RenameField(
            model_name='comunicado',
            old_name='general',
            new_name='es_general',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='grado',
            new_name='grado_asignado',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='seccion',
            new_name='seccion_asignada',
        ),
        migrations.RemoveField(
            model_name='designacion',
            name='docente_recibe',
        ),
        migrations.RemoveField(
            model_name='designacion',
            name='fecha_devolucion_prevista',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='equipo_principal',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_devolucion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_eliminacion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_registro_sistema',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='registrado_por',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='responsable',
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo',
            field=models.CharField(choices=[('INTERNA', 'Interna del Colegio'), ('EXTERNA', 'Participación Externa (Desfiles/Concursos)')], default='INTERNA', max_length=10),
        ),
        migrations.AddField(
            model_name='designacion',
            name='persona_responsable',
            field=models.CharField(default='Anonimo', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='aula_actual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nivel',
            field=models.CharField(choices=[('PRI', 'Primaria'), ('SEC', 'Secundaria')], default='General', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfil',
            name='esta_aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nivel_asignado',
            field=models.CharField(blank=True, choices=[('PRI', 'Primaria'), ('SEC', 'Secundaria')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='inventario.estudiante'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='designacion',
            name='aula_destino',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designacion',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventario.equipo'),
        ),
        migrations.AlterField(
            model_name='designacion',
            name='fecha_devolucion_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designacion',
            name='fecha_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(choices=[('LAPTOP', 'Laptop / Computadora'), ('SONIDO', 'Equipo de Sonido / Parlantes'), ('ELECTRO', 'Electrodoméstico'), ('ACCESORIO', 'Accesorio')], default='LAPTOP', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=15),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_ingreso_colegio',
            field=models.DateField(verbose_name='Fecha de Ingreso/Donación'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='inventario.estudiante'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador General'), ('DIRECTOR', 'Director del Colegio'), ('ENCAR', 'Profesor Encargado de Inventario'), ('DOCENTE', 'Docente Tutor'), ('SECRETARIA', 'Secretaria'), ('PADRE', 'Padre de Familia')], default='PADRE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('estudiante', 'fecha')},
        ),
    ]
